trigger:
- main

variables:
  - group: deploymentVars

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: inline
    workingDirectory: $(System.DefaultWorkingDirectory)
    script: |   
      line=$(sed -n '2p' debpkg)
      arr=( $line )
      ver="${arr[1]}"
      echo "##vso[task.setvariable variable=tempVer;]$ver"
  displayName: Get Package Version

- script: echo $(System.AccessToken) | az devops login
  displayName: Login to DevOps

- script: |
    az pipelines variable-group variable update --organization $(org) --project eggrollify --group-id 1 --name VERSION --value $(tempVer)
  displayName: Set version variable

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: $(System.DefaultWorkingDirectory)
    artifactName: $(artifactName)
  displayName: Publish Artifact