#!/bin/sh

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
BASE_DIR="$(basename $SCRIPT_DIR)"

if [ $BASE_DIR = 'bin' ]; then
    python3 "${SCRIPT_DIR}/../share/eggrollify.py" "$@"
else
    python3 "${SCRIPT_DIR}/eggrollify.py" "$@"
fi